### ISSUE TITLE
question: eslint Error: Failed to load config to extend from when config is in parent folder

### ISSUE THREAD

**Issue by mariusa** [antfu/vue-global-api#16]
Hi,

Thanks for this useful project!
Asking here since Discussions isn't activated:
.eslintrc.js extends 'vue-global-api' works fine when .eslintrc.js is in the same project folder.

But I'm using a shared  .eslintrc.js  which is up in the hierarchy.

To replicate with https://github.com/antfu/vitesse (I'm getting error with vue-global-api on my project, "@antfu" below is similar)
1. clone repo
2. move .eslintrc one parent folder up
3. open folder 'my-vitesse-app' in vscode
```
[Error - 12:24:24 PM] Error: Failed to load config "@antfu" to extend from. 
Referenced from: /home/marius/work/.eslintrc
    at configInvalidError (/home/marius/work/my-vitesse-app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/home/marius/work/my-vitesse-app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/home/marius/work/my-vitesse-app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/marius/work/my-vitesse-app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/home/marius/work/my-vitesse-app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/home/marius/work/my-vitesse-app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/home/marius/work/my-vitesse-app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/home/marius/work/my-vitesse-app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
```

I also installed `vue-global-api` both global as root and in project's pacakge.json
Other extends work fine, just vue-global-api errors: 
```
 extends: ["eslint:recommended", "plugin:vue/base", "plugin:vue/vue3-essential", "plugin:vue/vue3-recommended", "plugin:vue/vue3-strongly-recommended", "vue-global-api"],
```

Thanks for any hints. Feel free to close this issue, as it's not a vue-global-api problem, more of eslint config.

**Comment by mariusa** [comment]
Also tried to have a `~/.eslintrc.js` with everything, and an overwrite in `work/my-vitesse-app.eslintrc.js` with just

```
// http://eslint.org/docs/user-guide/configuring

module.exports = {
    extends: ["eslint:recommended", "plugin:vue/base", "plugin:vue/vue3-essential", "plugin:vue/vue3-recommended", "plugin:vue/vue3-strongly-recommended", "vue-global-api"]
      
}

```
This would be the best solution.
But, it loses everything specified in `~/.eslintrc.js`.

**Comment by mariusa** [comment]
Cause: 
`$ eslint --print-config ./.eslintrc`
`
(node:576365) [ESLINT_PERSONAL_CONFIG_SUPPRESS] DeprecationWarning: '~/.eslintrc.*' config files have been deprecated. Please remove it or add 'root:true' to the config files in your projects in order to avoid loading '~/.eslintrc.*' accidentally. (found in "../../../.eslintrc.js")
`
