### ISSUE TITLE
Error with yarn 1.22.5

### ISSUE THREAD

**Issue by byoungd** [antfu/vue-global-api#18]
OS info

```
Windows X64
yarn 1.22.5
```

Project config is vite with vue2

When I  add  'vue-global-api'  as dep

terminal complains about:

```
Pattern ["vue-demi@latest"] i
s trying to unpack in the same destin
ation "C:\\Users\\han\\AppData\\Local
\\Yarn\\Cache\\v6\\npm-vue-demi-0.11.
3-dd7495b92b495ecfa35675bf024b1358a7a
dd150-integrity\\node_modules\\vue-de
mi" as pattern ["vue-demi@*","vue-dem
i@*","vue-demi@*"]. This could result
 in non-deterministic behavior, skipp
ing.

```

I tried to lean yarn cache but vite start with errors:

```
onfig have changed)
 > node_modules/vue-global-api/onActivated.mjs:1:9
: error: No matching export in "node_modules/vue-d
emi/lib/index.mjs" for import "onActivated"       
    1 │ import { onActivated } from 'vue-demi'    
      ╵          ~~~~~~~~~~~

 > node_modules/vue-global-api/onBeforeMount.mjs:1
:9: error: No matching export in "node_modules/vue
-demi/lib/index.mjs" for import "onBeforeMount"   
    1 │ import { onBeforeMount } from 'vue-demi'  
      ╵          ~~~~~~~~~~~~~

 > node_modules/vue-global-api/onBeforeUnmount.mjs
:1:9: error: No matching export in "node_modules/v
ue-demi/lib/index.mjs" for import "onBeforeUnmount
"
    1 │ import { onBeforeUnmount } from 'vue-d... 
      ╵          ~~~~~~~~~~~~~~~

 > node_modules/vue-global-api/onBeforeUpdate.mjs:
1:9: error: No matching export in "node_modules/vu
e-demi/lib/index.mjs" for import "onBeforeUpdate" 
    1 │ import { onBeforeUpdate } from 'vue-demi' 
      ╵          ~~~~~~~~~~~~~~

 > node_modules/vue-global-api/onDeactivated.mjs:1
:9: error: No matching export in "node_modules/vue
-demi/lib/index.mjs" for import "onDeactivated"   
    1 │ import { onDeactivated } from 'vue-demi'  
      ╵          ~~~~~~~~~~~~~

 > node_modules/vue-global-api/onErrorCaptured.mjs
:1:9: error: No matching export in "node_modules/v
ue-demi/lib/index.mjs" for import "onErrorCaptured
"
    1 │ import { onErrorCaptured } from 'vue-d... 
      ╵          ~~~~~~~~~~~~~~~

 > node_modules/vue-global-api/onMounted.mjs:1:9: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "onMounted"
    1 │ import { onMounted } from 'vue-demi'      
      ╵          ~~~~~~~~~

 > node_modules/vue-global-api/onServerPrefetch.mj
s:1:9: error: No matching export in "node_modules/
vue-demi/lib/index.mjs" for import "onServerPrefet
ch"
    1 │ import { onServerPrefetch } from 'vue-... 
      ╵          ~~~~~~~~~~~~~~~~

 > node_modules/vue-global-api/onUnmounted.mjs:1:9
: error: No matching export in "node_modules/vue-d
emi/lib/index.mjs" for import "onUnmounted"       
    1 │ import { onUnmounted } from 'vue-demi'    
      ╵          ~~~~~~~~~~~

 > node_modules/vue-global-api/onUpdated.mjs:1:9: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "onUpdated"
    1 │ import { onUpdated } from 'vue-demi'      
      ╵          ~~~~~~~~~

 > node_modules/vue-global-api/computed.mjs:1:9: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "computed"
    1 │ import { computed } from 'vue-demi'       
      ╵          ~~~~~~~~

 > node_modules/vue-global-api/customRef.mjs:1:9: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "customRef"
    1 │ import { customRef } from 'vue-demi'      
      ╵          ~~~~~~~~~

 > node_modules/vue-global-api/isReadonly.mjs:1:9:
 error: No matching export in "node_modules/vue-de
mi/lib/index.mjs" for import "isReadonly"
    1 │ import { isReadonly } from 'vue-demi'     
      ╵          ~~~~~~~~~~

 > node_modules/vue-global-api/isRef.mjs:1:9: erro
r: No matching export in "node_modules/vue-demi/li
b/index.mjs" for import "isRef"
    1 │ import { isRef } from 'vue-demi'
      ╵          ~~~~~

 > node_modules/vue-global-api/markRaw.mjs:1:9: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "markRaw"
    1 │ import { markRaw } from 'vue-demi'        
      ╵          ~~~~~~~

 > node_modules/vue-global-api/reactive.mjs:1:9: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "reactive"
    1 │ import { reactive } from 'vue-demi'       
      ╵          ~~~~~~~~

 > node_modules/vue-global-api/readonly.mjs:1:9: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "readonly"
    1 │ import { readonly } from 'vue-demi'       
      ╵          ~~~~~~~~

 > node_modules/vue-global-api/ref.mjs:1:9: error:
 No matching export in "node_modules/vue-demi/lib/
index.mjs" for import "ref"
    1 │ import { ref } from 'vue-demi'
      ╵          ~~~

 > node_modules/vue-global-api/shallowReactive.mjs
:1:9: error: No matching export in "node_modules/v
ue-demi/lib/index.mjs" for import "shallowReactive
"
    1 │ import { shallowReactive } from 'vue-d... 
      ╵          ~~~~~~~~~~~~~~~

 > node_modules/vue-global-api/shallowReadonly.mjs
:1:9: error: No matching export in "node_modules/v
ue-demi/lib/index.mjs" for import "shallowReadonly
"
    1 │ import { shallowReadonly } from 'vue-d... 
      ╵          ~~~~~~~~~~~~~~~

 > node_modules/vue-global-api/shallowRef.mjs:1:9:
 error: No matching export in "node_modules/vue-de
mi/lib/index.mjs" for import "shallowRef"
    1 │ import { shallowRef } from 'vue-demi'     
      ╵          ~~~~~~~~~~

 > node_modules/vue-global-api/toRaw.mjs:1:9: erro
r: No matching export in "node_modules/vue-demi/li
b/index.mjs" for import "toRaw"
    1 │ import { toRaw } from 'vue-demi'
      ╵          ~~~~~

 > node_modules/vue-global-api/toRef.mjs:1:9: erro
r: No matching export in "node_modules/vue-demi/li
b/index.mjs" for import "toRef"
    1 │ import { toRef } from 'vue-demi'
      ╵          ~~~~~

 > node_modules/vue-global-api/toRefs.mjs:1:9: err
or: No matching export in "node_modules/vue-demi/l
ib/index.mjs" for import "toRefs"
    1 │ import { toRefs } from 'vue-demi'
      ╵          ~~~~~~

 > node_modules/vue-global-api/triggerRef.mjs:1:9:
 error: No matching export in "node_modules/vue-de
mi/lib/index.mjs" for import "triggerRef"
    1 │ import { triggerRef } from 'vue-demi'     
      ╵          ~~~~~~~~~~

 > node_modules/vue-global-api/unref.mjs:1:9: erro
r: No matching export in "node_modules/vue-demi/li
b/index.mjs" for import "unref"
    1 │ import { unref } from 'vue-demi'
      ╵          ~~~~~

 > node_modules/vue-global-api/watch.mjs:1:9: erro
r: No matching export in "node_modules/vue-demi/li
b/index.mjs" for import "watch"
    1 │ import { watch } from 'vue-demi'
      ╵          ~~~~~

 > node_modules/vue-global-api/watchEffect.mjs:1:9
: error: No matching export in "node_modules/vue-d
emi/lib/index.mjs" for import "watchEffect"       
    1 │ import { watchEffect } from 'vue-demi'    
      ╵          ~~~~~~~~~~~

 > node_modules/vue-global-api/defineComponent.mjs
:1:9: error: No matching export in "node_modules/v
ue-demi/lib/index.mjs" for import "defineComponent
"
    1 │ import { defineComponent } from 'vue-d... 
      ╵          ~~~~~~~~~~~~~~~

 > node_modules/vue-global-api/defineAsyncComponen
t.mjs:1:9: error: No matching export in "node_modu
les/vue-demi/lib/index.mjs" for import "defineAsyn
cComponent"
    1 │ import { defineAsyncComponent } from '... 
      ╵          ~~~~~~~~~~~~~~~~~~~~

 > node_modules/vue-global-api/getCurrentInstance.
mjs:1:9: error: No matching export in "node_module
s/vue-demi/lib/index.mjs" for import "getCurrentIn
stance"
    1 │ import { getCurrentInstance } from 'vu... 
      ╵          ~~~~~~~~~~~~~~~~~~

 > node_modules/vue-global-api/h.mjs:1:9: error: N
o matching export in "node_modules/vue-demi/lib/in
dex.mjs" for import "h"
    1 │ import { h } from 'vue-demi'
      ╵          ^

 > node_modules/vue-global-api/inject.mjs:1:9: err
or: No matching export in "node_modules/vue-demi/l
ib/index.mjs" for import "inject"
    1 │ import { inject } from 'vue-demi'
      ╵          ~~~~~~

 > node_modules/vue-global-api/nextTick.mjs:1:9: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "nextTick"
    1 │ import { nextTick } from 'vue-demi'       
      ╵          ~~~~~~~~

 > node_modules/vue-global-api/provide.mjs:1:9: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "provide"
    1 │ import { provide } from 'vue-demi'        
      ╵          ~~~~~~~

 > node_modules/vue-global-api/useCssModule.mjs:1:
9: error: No matching export in "node_modules/vue-
demi/lib/index.mjs" for import "useCssModule"     
    1 │ import { useCssModule } from 'vue-demi'   
      ╵          ~~~~~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:9: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "computed"
    1 │ import { computed, unref, watch, ref, ... 
      ╵          ~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:19: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "unref"
    1 │ ...rt { computed, unref, watch, ref, c... 
      ╵                   ~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:26: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "watch"
    1 │ ...mputed, unref, watch, ref, customRe... 
      ╵                   ~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:33: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "ref"
    1 │ ..., unref, watch, ref, customRef, isV... 
      ╵                    ~~~

 > node_modules/@vueuse/shared/index.esm.js:1:38: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "customRef"
    1 │ ... watch, ref, customRef, isVue3, isR... 
      ╵                 ~~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:57: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "isRef"
    1 │ ...omRef, isVue3, isRef, reactive, toR... 
      ╵                   ~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:64: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "reactive"
    1 │ ...sVue3, isRef, reactive, toRef, isVu... 
      ╵                  ~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:74: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "toRef"
    1 │ ...Ref, reactive, toRef, isVue2, getCu... 
      ╵                   ~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:89: 
error: No matching export in "node_modules/vue-dem
i/lib/index.mjs" for import "getCurrentInstance"  
    1 │ ... isVue2, getCurrentInstance, onMoun... 
      ╵             ~~~~~~~~~~~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:109:
 error: No matching export in "node_modules/vue-de
mi/lib/index.mjs" for import "onMounted"
    1 │ ...entInstance, onMounted, nextTick, o... 
      ╵                 ~~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:120:
 error: No matching export in "node_modules/vue-de
mi/lib/index.mjs" for import "nextTick"
    1 │ ...e, onMounted, nextTick, onUnmounted... 
      ╵                  ~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:130:
 error: No matching export in "node_modules/vue-de
mi/lib/index.mjs" for import "onUnmounted"        
    1 │ ..., nextTick, onUnmounted } from 'vue... 
      ╵                ~~~~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:9: err
or: No matching export in "node_modules/vue-demi/l
ib/index.mjs" for import "isRef"
    1 │ import { isRef, ref, watchEffect, comp... 
      ╵          ~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:16: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "ref"
    1 │ import { isRef, ref, watchEffect, comp... 
      ╵                 ~~~

 > node_modules/@vueuse/core/index.esm.js:1:21: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "watchEffect"
    1 │ ...isRef, ref, watchEffect, computed, ... 
      ╵                ~~~~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:34: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "computed"
    1 │ ... watchEffect, computed, customRef, ... 
      ╵                  ~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:44: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "customRef"
    1 │ ...t, computed, customRef, unref, inje... 
      ╵                 ~~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:55: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "unref"
    1 │ ...ed, customRef, unref, inject, creat... 
      ╵                   ~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:62: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "inject"
    1 │ ...tomRef, unref, inject, createApp, r... 
      ╵                   ~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:70: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "createApp"
    1 │ ...ref, inject, createApp, reactive, w... 
      ╵                 ~~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:81: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "reactive"
    1 │ ...t, createApp, reactive, watch, getC... 
      ╵                  ~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:91: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "watch"
    1 │ ...App, reactive, watch, getCurrentIns... 
      ╵                   ~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:98: er
ror: No matching export in "node_modules/vue-demi/
lib/index.mjs" for import "getCurrentInstance"    
    1 │ ..., watch, getCurrentInstance, onMoun... 
      ╵             ~~~~~~~~~~~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:118: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "onMounted"
    1 │ ...entInstance, onMounted, onUpdated, ... 
      ╵                 ~~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:129: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "onUpdated"
    1 │ ..., onMounted, onUpdated, toRefs as t... 
      ╵                 ~~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:140: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "toRefs"
    1 │ ...ed, onUpdated, toRefs as toRefs$1, ... 
      ╵                   ~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:160: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "shallowRef"
    1 │ ...as toRefs$1, shallowRef, markRaw, r... 
      ╵                 ~~~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:172: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "markRaw"
    1 │ ..., shallowRef, markRaw, readonly, on... 
      ╵                  ~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:181: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "readonly"
    1 │ ...Ref, markRaw, readonly, onBeforeUpd... 
      ╵                  ~~~~~~~~

 > node_modules/@vueuse/core/index.esm.js:1:191: e
rror: No matching export in "node_modules/vue-demi
/lib/index.mjs" for import "onBeforeUpdate"       
    1 │ ... readonly, onBeforeUpdate, isVue2 }... 
      ╵               ~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 66 errors:
node_modules/@vueuse/core/index.esm.js:1:9: error:
 No matching export in "node_modules/vue-demi/lib/
index.mjs" for import "isRef"
node_modules/@vueuse/core/index.esm.js:1:16: error
: No matching export in "node_modules/vue-demi/lib
/index.mjs" for import "ref"
node_modules/@vueuse/core/index.esm.js:1:21: error
: No matching export in "node_modules/vue-demi/lib
/index.mjs" for import "watchEffect"
node_modules/@vueuse/core/index.esm.js:1:34: error
: No matching export in "node_modules/vue-demi/lib
/index.mjs" for import "computed"
node_modules/@vueuse/core/index.esm.js:1:44: error
: No matching export in "node_modules/vue-demi/lib
/index.mjs" for import "customRef"
...
    at failureErrorWithLog (D:\DEV\fb-desktop-ssr\
node_modules\esbuild\lib\main.js:1449:15)
    at D:\DEV\fb-desktop-ssr\node_modules\esbuild\
lib\main.js:1131:28
    at runOnEndCallbacks (D:\DEV\fb-desktop-ssr\no
de_modules\esbuild\lib\main.js:921:63)
    at buildResponseToResult (D:\DEV\fb-desktop-ss
r\node_modules\esbuild\lib\main.js:1129:7)        
    at D:\DEV\fb-desktop-ssr\node_modules\esbuild\
lib\main.js:1236:14
    at D:\DEV\fb-desktop-ssr\node_modules\esbuild\
lib\main.js:609:9
    at handleIncomingPacket (D:\DEV\fb-desktop-ssr
\node_modules\esbuild\lib\main.js:706:9)
    at Socket.readFromStdout (D:\DEV\fb-desktop-ss
r\node_modules\esbuild\lib\main.js:576:7)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9
)
    at Socket.Readable.push (_stream_readable.js:2
13:10)
    at Pipe.onStreamRead (internal/stream_base_com
mons.js:188:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for
 documentation about this command.
```

**Comment by byoungd** [comment]
Use npm instead solves this problem but and I am not sure it's a bug of yarn or something else with vue-gloabl-api.
Hope I can provide more information about this.
thanks!

**Comment by antfu** [comment]
Have you installed `@vue/composition-api`?

**Comment by byoungd** [comment]
> Have you installed `@vue/composition-api`?

Yeah, `@vue/composition-api` is installed.

 It wroks fine on MacOS even if it has the same complain `Pattern ["vue-demi@latest"] is trying to unpack in the same destination`. 

I will collect more information if I figured it out.

**Comment by wobsoriano** [comment]
In nuxt I fixed this by adding `vue-global-api` in the [transpile array](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build)

```js
build: {
  transpile: ['vue-global-api'],
},
```

I guess for vue-cli and vue 2 you can create a `vue.config.js` file and add it to [transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies)

I'm using yarn `1.22.10`

**Comment by byoungd** [comment]
> In nuxt I fixed this by adding `vue-global-api` in the [transpile array](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build)
> 
> ```js
> build: {
>   transpile: ['vue-global-api'],
> },
> ```
> 
> I guess for vue-cli and vue 2 you can create a `vue.config.js` file and add it to [transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies)
> 
> I'm using yarn `1.22.10`

Thanks for providing this useful information I will try later.
